joint_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
  interface_name: position
  state_publish_rate: 50
  action_monitor_rate: 20
  allow_partial_joints_goal: false
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.01
    joint1: { trajectory: 0.05, goal: 0.02 }
    joint2: { trajectory: 0.05, goal: 0.02 }
    joint3: { trajectory: 0.05, goal: 0.02 }
